- name: Demo
  hosts: localhost
  tasks:
    - name: print Hello World
      ansible.builtin.debug:
        msg: hello world
- name: Demo on vars
  hosts: localhost
  vars:
    URL: example.com
  tasks:
    - name: print  a variable
      ansible.builtin.debug:
        msg: "{{ URL }}"
- name: Demo on task level vars
  hosts: localhost
  vars:
    URL: example.com
  tasks:
    - name: print  a variable
      ansible.builtin.debug:
        msg: "{{ URL }}"
      vars:
        URL: example.com