- name: print Used Memory
  hosts: localhost
  tasks:
   - name: Get Memory
     ansible.builtin.shell: free | grep Mem
     register: free
   - name: print free variable
     ansible.builtin.set_fact:
      FREE: "{{ free.stdout | split(' ') }}"
   - name: set fact
     ansible.builtin.set_fact:
       total: "{{ FREE[1] }}"
       free: "{{ FREE[3] }}"
       used_mem: "{{ 100 - (FREE[3]|int / FREE[1]|int * 100) }}"
   - name: print free output
     ansible.builtin.debug:
       msg: "{{ used_mem }}"