- name: Demo on Parameter
  hosts: localhost
  tasks:
    - name: Get a parameter from Parameter Store
      ansible.builtin.debug:
        mdg: "{{ lookup('aws_ssm', 'test', region='us-east-1' ) }}"
